/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 JapaneseRoom.glb 
Author: abot86 (https://sketchfab.com/abot86)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-tatami-room-89d9cd7d90724d4d8463b6cfc652620d
Title: Japanese Tatami Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/JapaneseRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.435, 3.33, 0]} scale={[7.51, 4.529, 7.035]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.light_mat_color} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.wood} />
      </group>
      <group position={[-6.694, 9.143, 5.448]} scale={[1, 1, 1.536]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-6.71, 9.179, -3.187]} scale={[1, 1, 3.416]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['light_mat_color.002']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.wood} />
      </group>
      <group position={[-6.694, 9.143, 2.339]} scale={[1, 1, 1.536]}>
        <mesh geometry={nodes.Object_57.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-6.694, 0.016, 5.448]} scale={[1, 1, 1.536]}>
        <mesh geometry={nodes.Object_68.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-6.694, 0.016, 2.339]} scale={[1, 1, 1.536]}>
        <mesh geometry={nodes.Object_71.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-6.694, 0.016, -1.423]} scale={[1, 1, 1.697]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-6.694, 0.016, -4.857]} scale={[1, 1, 1.697]}>
        <mesh geometry={nodes.Object_79.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.light_mat_color} />
      </group>
      <group position={[-0.091, 8.539, -6.973]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.393, 0.072, 1.393]}>
        <mesh geometry={nodes.Object_84.geometry} material={materials.Lightwood} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Material} />
      </group>
      <group position={[-17.713, 6.727, -0.861]} rotation={[Math.PI / 2, 0, -2.008]} scale={1.192}>
        <mesh geometry={nodes.Object_157.geometry} material={materials.Vase} position={[-7.036, 12.992, 4.831]} rotation={[0, 0, -0.43]} scale={0.377} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.Vase} position={[-7.036, 12.992, 4.831]} rotation={[0, 0, -0.43]} scale={0.377} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials.wood} position={[1.277, -1.405, -0.104]} scale={[0.315, 1.854, 0.315]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.wood} position={[1.249, 0.376, -0.106]} scale={[2.66, 0.143, 1.783]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Plate} position={[1.318, -0.873, 2.808]} scale={[1, 0.052, 1]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.seat_cushion} position={[1.318, -0.781, 2.808]} scale={[0.863, 0.084, 0.863]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Plate} position={[1.318, 0.03, 3.864]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.052, 1]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Plate} position={[1.318, -0.851, -2.975]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.052, 1]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.seat_cushion} position={[1.318, -0.782, -2.975]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.863, 0.084, 0.863]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.wood} position={[-6.436, 1.015, 3.891]} scale={[1, 0.526, 0.094]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.wood} position={[-6.691, 2.94, 0.537]} scale={[1, 5.09, 0.206]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Stone} position={[-6.802, 1.15, -1.775]} scale={[0.147, 0.147, 0.165]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Vase} position={[-6.587, 1.89, -5.7]} scale={[0.349, 0.965, 0.349]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Stone} position={[6.186, -0.715, -6.61]} scale={[1.1, 0.525, 0.464]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Material.003']} position={[6.211, 3.254, -6.91]} scale={[0.871, 2.811, 0.054]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Material.004']} position={[6.219, 0.485, -6.836]} rotation={[0, 0, -Math.PI / 2]} scale={[0.104, 0.9, 0.109]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Material.004']} position={[6.219, 6.04, -6.836]} rotation={[0, 0, -Math.PI / 2]} scale={[0.104, 0.9, 0.109]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material} position={[4.581, -0.92, 2.78]} scale={[2.195, 1.295, 4.081]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.material} position={[-3.776, -0.905, 3.068]} scale={[1.702, 1.38, 3.745]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.material} position={[2.542, -0.915, -3.816]} rotation={[0, Math.PI / 2, 0]} scale={[2.287, 1.334, 4.33]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.material} position={[-3.789, -0.922, -3.584]} scale={[1.678, 1.354, 2.527]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material} position={[0.086, -0.922, 4.253]} scale={[1.838, 1.288, 2.583]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Plate} position={[1.318, 0.03, -3.989]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 0.052, 1]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Plate} position={[1.278, 0.554, -0.175]} scale={[1, 0.053, 1]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.wood} position={[-6.691, 2.94, -6.811]} scale={[1, 5.09, 0.206]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.wood} position={[1.086, 6.744, -6.996]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.535, 6.397, 0.094]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.wood} position={[7.415, 2.135, -7.126]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 4.518, 0.089]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.wood} position={[5.017, 2.135, -7.126]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 4.518, 0.089]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.lamp} position={[-6.326, 6.69, -3.261]} scale={0.59} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.wood} position={[-6.944, 3.339, 6.987]} scale={[1, 4.61, 0.066]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.wood} position={[-5.242, 2.135, -7.126]} rotation={[0, Math.PI / 2, 0]} scale={[0.168, 4.518, 0.089]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials['Material.002']} position={[-6.623, 10.143, 6.042]} scale={[0.856, 1, 1]} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Lightwood} position={[-0.093, 9.397, -6.895]} scale={[1.034, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.Lightwood} position={[-0.093, 8.85, -6.895]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Lightwood} position={[-0.631, 8.521, -6.895]} rotation={[0, 0, -Math.PI / 2]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.Lightwood} position={[0.526, 8.521, -6.895]} rotation={[0, 0, -Math.PI / 2]} scale={[1.168, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials.Material} position={[3.191, 4.913, -6.94]} scale={[1.726, 1.726, 0.061]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.wood} position={[-0.04, 5.759, -6.996]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1.584, 6.397, 0.094]} />
      <mesh geometry={nodes.Object_103.geometry} material={materials.Material} position={[-1.861, 4.913, -6.967]} scale={[1.726, 1.726, 0.014]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.wood} position={[3.254, 4.934, -6.903]} scale={[1.726, 1.799, 0.051]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.wood} position={[-1.84, 4.913, -6.994]} scale={[1.726, 1.78, 0.051]} />
      <mesh geometry={nodes.Object_109.geometry} material={materials.Leaves} position={[-5.855, 4.451, -4.454]} rotation={[0.518, 0.986, -0.469]} scale={[0.153, 0.183, 0.183]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.Leaves} position={[-6.23, 4.095, -5.24]} rotation={[0.933, 1.214, -0.737]} scale={[0.091, 0.108, 0.108]} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.Leaves} position={[-6.262, 3.84, -5.615]} rotation={[-1.285, 1.344, 1.475]} scale={[0.143, 0.171, 0.171]} />
      <mesh geometry={nodes.Object_115.geometry} material={materials.Leaves} position={[-6.229, 4.487, -3.083]} rotation={[0.681, 0.816, -0.213]} scale={[0.228, 0.271, 0.271]} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.Leaves} position={[-6.296, 4.032, -3.994]} rotation={[0.687, 0.823, -0.222]} scale={[0.19, 0.226, 0.226]} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.Leaves} position={[-6.289, 3.409, -4.598]} rotation={[0.73, 0.867, -0.279]} scale={[0.156, 0.186, 0.186]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.Leaves} position={[-6.289, 3.066, -5.243]} rotation={[0.767, 0.899, -0.326]} scale={[0.134, 0.159, 0.159]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.Leaves} position={[-6.576, 5.437, -5.22]} rotation={[-3.043, 0.748, -3.082]} scale={[0.216, 0.271, 0.26]} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.Leaves} position={[-6.264, 4.821, -4.424]} rotation={[0.59, 1.325, -0.644]} scale={[0.169, 0.229, 0.228]} />
      <mesh geometry={nodes.Object_127.geometry} material={materials.Leaves} position={[-5.462, 5.012, -4.898]} rotation={[-0.012, 1.267, -0.012]} scale={[0.202, 0.305, 0.3]} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.Lightwood} position={[-0.093, 7.874, -6.895]} scale={[1.118, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_131.geometry} material={materials.Lightwood} position={[-0.114, 8.521, -6.895]} rotation={[0, 0, -Math.PI / 2]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.Lightwood} position={[-0.093, 9.297, -6.895]} scale={[1.085, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.Lightwood} position={[-0.093, 7.769, -6.895]} scale={[1.118, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.Lightwood} position={[-0.001, 8.521, -6.894]} rotation={[0, 0, -Math.PI / 2]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_139.geometry} material={materials.Lightwood} position={[0.983, 8.374, -6.895]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.Lightwood} position={[0.871, 8.723, -6.889]} scale={[0.347, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.Lightwood} position={[-0.093, 8.605, -6.895]} scale={[1.242, 0.031, 0.027]} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.Lightwood} position={[-0.717, 8.49, -6.897]} scale={[0.348, 0.032, 0.028]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials['Material.002']} position={[-6.543, 2.879, -5.695]} rotation={[0.228, -0.364, 1.583]} />
      <mesh geometry={nodes.Object_149.geometry} material={materials['Material.002']} position={[-6.54, 3.328, -5.45]} rotation={[0.213, -0.056, 1.513]} />
      <mesh geometry={nodes.Object_151.geometry} material={materials['Material.002']} position={[-6.142, 3.335, -5.303]} rotation={[0.239, 0.471, 1.39]} />
      <mesh geometry={nodes.Object_153.geometry} material={materials['Material.002']} position={[-6.605, 3.313, -5.275]} rotation={[0.357, -0.389, 1.55]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.Vase} position={[1.011, 0.889, 0.14]} scale={[0.116, 0.142, 0.116]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.Vase} position={[1.816, 0.898, -0.258]} scale={[0.12, 0.147, 0.12]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.Copper} position={[-5.663, 0.149, 6.597]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.Copper} position={[-5.663, 0.149, 1.338]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.Copper} position={[-5.663, 0.149, -0.265]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.Copper} position={[-5.663, 0.149, -6.011]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.Copper} position={[-5.663, 7.25, 6.597]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Copper} position={[-5.663, 7.25, 1.297]} rotation={[0, 0, -Math.PI / 2]} scale={[0.109, 0.115, 0.115]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.plate_decoration} position={[-7.104, 2.164, -1.378]} rotation={[0, 0, -1.197]} scale={[0.943, 0.057, 0.943]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.wood} position={[1.253, -1.143, 0.719]} scale={6.238} />
      <mesh geometry={nodes.Object_182.geometry} material={materials['Material.005']} position={[12.601, 21.419, 12.37]} rotation={[Math.PI / 2, 0, -Math.PI / 4]} scale={[7.999, 7.492, 7.492]} />
    </group>
  )
}

useGLTF.preload('/JapaneseRoom.glb')
