/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LivingRoom.glb 
Author: Vladek (https://sketchfab.com/vladek27)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-living-room-df179eebec234798aa7fbe6c7eaf492a
Title: Low poly living room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LivingRoom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/LivingRoom.glb')
