/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Mugi.glb 
Author: Coffeek (https://sketchfab.com/coffe0wolf)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mugi-632ffc64662c4303b2ddf41f4d0fc5c9
Title: Mugi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mugi.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.leaves} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.veil} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mugi.glb')
